// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXkSrkOmRnvAZs0qFrykqWbx0r-4iFzxQ',
    appId: '1:83953880984:android:141e8ca9ce9561970ca5ed',
    messagingSenderId: '83953880984',
    projectId: 'playground-fddba',
    databaseURL: 'https://playground-fddba.firebaseio.com',
    storageBucket: 'playground-fddba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkEFs_Jn7M0xT_PGT5Ou4Yh_RDu3I41gI',
    appId: '1:83953880984:ios:efe89102f5e4f79a0ca5ed',
    messagingSenderId: '83953880984',
    projectId: 'playground-fddba',
    databaseURL: 'https://playground-fddba.firebaseio.com',
    storageBucket: 'playground-fddba.firebasestorage.app',
    androidClientId: '83953880984-2kgqvj68oau5icijds6flgc1qqqhnqdc.apps.googleusercontent.com',
    iosClientId: '83953880984-2i9er9ido7q0nhscgepuskjpta0o31td.apps.googleusercontent.com',
    iosBundleId: 'dev.elainedb.flutter-junie',
  );

}